{% set version = "2.6.2" %}
{% set commit = "5959b8783e45f1809812ed96ae762f38ee701972" %}
package:
  name: magma
  version: {{ version }}
source:
  git_url: https://bitbucket.org/icl/magma.git
  git_rev: 5959b8783e45f1809812ed96ae762f38ee701972
requirements:
  build:
    - python
    - make
    - libstdcxx-ng
    - libgcc-ng
    - rocm-dev
  run:
    - python
    - libstdcxx-ng
    - libgcc-ng
    - rocm-dev