cd test
bash run-hip.sh
bash run-miopen-img.sh
bash run-miopen.sh
bash run-rocblas.sh
bash run-rocblas2.sh
bash run-rocfft.sh
bash run-rocrand.sh
bash run-rocsparse.sh
bash run-opencl.sh
bash run-opencl2.sh
bash run-opencl3.sh