{% set version = "0.1" %}
{% set conda_rocm_version = environ.get('CONDA_ROCM_VERSION', '5.1.0') %}
{% set apex_commit_sha = environ.get('APEX_COMMIT_SHA', '') %}
{% set apex_branch = environ.get('APEX_BRANCH', '') %}
{% set apex_proc_type = "gpu" %}
{% set string_a = environ.get('PACKAGES_BUILD_STRING_A', '') %}
{% set string_b = environ.get('PACKAGES_BUILD_STRING_B', '') %}
{% if string_b != '' %}
  {% set string_b = '_' + string_b %}
{% endif %}

package:
  name: apex
  version: {{ version }}
source:
{% if apex_commit_sha != '' %}
  url: https://github.com/ROCmSoftwarePlatform/apex/archive/{{ apex_commit_sha }}.tar.gz
{% elif apex_branch != '' %}
  url: https://github.com/ROCmSoftwarePlatform/apex/archive/{{ apex_branch }}.tar.gz
{% else %}
  git_url: https://github.com/ROCmSoftwarePlatform/apex.git
{% endif %}
build:
  number: 0
  skip: True  # [osx or win]
{% if string_a != '' %}
  string: +{{ string_a }}_py{{ CONDA_PY }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% else %}
  string: py{{ CONDA_PY }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% endif %}
outputs:
  - name: apex-proc
    version: {{ version }}
    build:
      string: "{{ apex_proc_type }}"
    test:
      commands:
        - exit 0

  - name: apex
    version: {{ version }}
    build:
      script: python -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pytorch
        - setuptools
        - pip
        - rocm-dev
      run:
        - python
        - cxxfilt  # [linux]
        - tqdm
        - numpy
        - PyYAML
        - pytest
      run_constrained:
        - apex-proc * {{ apex_proc_type }}
        - pytorch
    test:
      imports:
        - apex
        - apex.amp
        - apex.parallel
        - apex.optimizers
        - apex.normalization.fused_layer_norm