{% set version = "0.1" %}
{% set commit = "088985936518be7e25795a30d8ab33affa9db6ed" %}
{% set nvidia_apex_proc_type = "gpu" %}

package:
  name: nvidia-apex
  version: {{ version }}
source:
  url: https://github.com/NVIDIA/apex/archive/{{ commit }}.tar.gz
  sha256: cc5ce27aa30b5ade54d520fafc1cd7d293dfba58c51851759a034d03e3f370bb
build:
  number: 0
  skip: True  # [osx or win]
outputs:
  - name: nvidia-apex-proc
    version: {{ version }}
    build:
      string: "{{ nvidia_apex_proc_type }}"
    test:
      commands:
        - exit 0

  - name: nvidia-apex
    version: {{ version }}
    build:
      script: python -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pytorch
        - setuptools
        - pip
        - rocm-dev
      run:
        - python
        - cxxfilt  # [linux]
        - tqdm
        - numpy
        - PyYAML
        - pytest
      run_constrained:
        - nvidia-apex-proc * {{ nvidia_apex_proc_type }}
        - pytorch
    test:
      imports:
        - apex
        - apex.amp
        - apex.parallel
        - apex.optimizers
        - apex.normalization.fused_layer_norm