{% set version = "1.0.0" %}

package:
  name: pytorch
  version: {{ version }}
source:
  git_url: https://github.com/ROCmSoftwarePlatform/pytorch.git
  patches:
    - set-rocm_source_dir.patch
build:
  number: 0
  script_env:
    - CMAKE_ARGS
    - CFLAGS
    - CMAKE_PREFIX_PATH
    - HIP_PATH
    - ROCM_PATH
    - ROCM_SOURCE_DIR
    - ROCTRACER_INCLUDE_DIR
    - USE_ROCM
    - USE_NINJA
  missing_dso_whitelist:
    - $RPATH/libtorch.so
    - $RPATH/libtorch_cpu.so
    - $RPATH/libtorch_hip.so
    - $RPATH/libc10.so
    - $RPATH/libc10_hip.so
    - $RPATH/libjitbackend_test.so
    - $RPATH/libbackend_with_compiler.so
test:
  files:
    - test
  imports:
    - torch
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - git
    - patch
    - zlib
    - astunparse
    - numpy
    - ninja
    - pyyaml
    - mkl
    - mkl-include
    - setuptools
    - cmake
    - make
    - cffi
    - typing_extensions
    - future
    - six
    - requests
    - dataclasses
    - numactl-cos6-x86_64
    - numactl-devel-cos6-x86_64
    - elfutils
    - libdrm
    - rocm-dev
    - rocm-hip-sdk
    - rocm-ml-libraries

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - numpy
    - cffi
    - protobuf
    - tabulate
    - future
    - pillow
    - typing_extensions
    - networkx
    - numactl-cos6-x86_64
    - numactl-devel-cos6-x86_64
    - scipy
    - lmdb
    - leveldb
    - pyyaml
    - mkl
    - rocm-hip-runtime
    - rocm-ml-libraries
    - rocm-dev