{% set conda_rocm_version = environ.get('CONDA_ROCM_VERSION', '5.1.0') %}
{% set pytorch_commit_sha = environ.get('PYTORCH_COMMIT_SHA', '') %}
{% set pytorch_branch = environ.get('PYTORCH_BRANCH', '') %}
{% set version = environ.get('PYTORCH_VERSION', '1.0') %}
{% set string_a = environ.get('PACKAGES_BUILD_STRING_A', '') %}
{% set string_b = environ.get('PACKAGES_BUILD_STRING_B', '') %}
{% if string_b != '' %}
  {% set string_b = '_' + string_b %}
{% endif %}

package:
  name: pytorch
  version: {{ version }}
source:
{% if pytorch_commit_sha != '' %}
  url: https://github.com/ROCmSoftwarePlatform/pytorch/archive/{{ pytorch_commit_sha }}.tar.gz
{% elif pytorch_branch != '' %}
  url: https://github.com/ROCmSoftwarePlatform/pytorch/archive/{{ pytorch_branch }}.tar.gz
{% else %}
  git_url: https://github.com/ROCmSoftwarePlatform/pytorch.git
{% endif %}
  patches:
    - set-rocm_source_dir.patch
build:
  number: 0
{% if string_a != '' %}
  string: +{{ string_a }}_py{{ CONDA_PY }}_rocm{{ conda_rocm_version }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% elif pytorch_commit_sha != '' %}
  string: +git{{ pytorch_commit_sha }}_py{{ CONDA_PY }}_rocm{{ conda_rocm_version }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% elif pytorch_branch != '' %}
  string: +dev{{ pytorch_branch }}_py{{ CONDA_PY }}_rocm{{ conda_rocm_version }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% else %}
  string: py{{ CONDA_PY }}_rocm{{ conda_rocm_version }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% endif %}
  script_env:
    - CMAKE_ARGS
    - CFLAGS
    - CMAKE_PREFIX_PATH
    - HIP_PATH
    - ROCM_PATH
    - ROCM_SOURCE_DIR
    - ROCTRACER_INCLUDE_DIR
    - USE_ROCM
    - USE_NINJA
  missing_dso_whitelist:
    - $RPATH/libtorch.so
    - $RPATH/libtorch_cpu.so
    - $RPATH/libtorch_hip.so
    - $RPATH/libc10.so
    - $RPATH/libc10_hip.so
    - $RPATH/libjitbackend_test.so
    - $RPATH/libbackend_with_compiler.so
test:
  files:
    - test
  imports:
    - torch
requirements:
  build:
    - python
    - git
    - patch
    - zlib
    - astunparse
    - numpy
    - ninja
    - pyyaml
    - mkl <2022
    - mkl-include <2022
    - ncurses <6
    - setuptools
    - cmake
    - make
    - cffi
    - typing_extensions
    - future
    - six
    - requests
    - dataclasses
    - numactl-cos6-x86_64
    - numactl-devel-cos6-x86_64
    - elfutils
    - libdrm
    - rocm-dev =={{ conda_rocm_version }}
    - rocm-hip-sdk =={{ conda_rocm_version }}
    - rocm-ml-libraries =={{ conda_rocm_version }}

  run:
    - python
    - numpy
    - cffi
    - protobuf
    - tabulate
    - future
    - pillow
    - typing_extensions
    - networkx
    - numactl-cos6-x86_64
    - numactl-devel-cos6-x86_64
    - scipy
    - lmdb
    - leveldb
    - pyyaml
    - mkl <2022
    - mkl-include <2022
    - rocm-hip-runtime =={{ conda_rocm_version }}
    - rocm-ml-libraries =={{ conda_rocm_version }}
    - rocm-dev =={{ conda_rocm_version }}