{% set version = environ.get('CONDA_ROCM_VERSION', '5.1.0') %}
package:
  name: rocm-hip-sdk
  version: {{ version }}
source:
  path: .
build:
  missing_dso_whitelist:
    - $RPATH/librt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libpthread.so.0
    - $RPATH/libtinfo.so.5
    - $RPATH/libm.so.6
    - $RPATH/libc.so.6
    - $RPATH/libelf.so.1
    - $RPATH/libdrm.so.2
    - $RPATH/libdrm_amdgpu.so.1
    - $RPATH/libnuma.so.1
    - /lib64/ld-linux-x86-64.so.2
  script: |
    python build.py --rocmrelease={{ version }}
test:
  requires:
    - rocm-dev
  files:
    - test
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - zlib
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python