package:
  name: rocblas
  version: 5.1.0
source:
  path: .
build:
  missing_dso_whitelist:
    - $RPATH/librt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libpthread.so.0
    - $RPATH/libtinfo.so.5
    - $RPATH/libm.so.6
    - $RPATH/libc.so.6
    - $RPATH/libelf.so.1
    - $RPATH/libdrm.so.2
    - $RPATH/libdrm_amdgpu.so.1
    - $RPATH/libnuma.so.1
    - $RPATH/libamdhip64.so.5
    - /lib64/ld-linux-x86-64.so.2
  script: |
    python build.py --rocmrelease=5.1.0
requirements:
  build:
    - python
    - libstdcxx-ng
    - libgcc-ng
    - zlib
  run:
    - python
    - libstdcxx-ng
    - libgcc-ng