package:
  name: rocm-ml-libraries
  version: 5.1.0
source:
  path: .
build:
  no_link:
    - rocblas/*
  missing_dso_whitelist:
    - $RPATH/librt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libpthread.so.0
    - $RPATH/libtinfo.so.5
    - $RPATH/libm.so.6
    - $RPATH/libc.so.6
    - $RPATH/libelf.so.1
    - $RPATH/libdrm.so.2
    - $RPATH/libdrm_amdgpu.so.1
    - $RPATH/libnuma.so.1
    - /lib64/ld-linux-x86-64.so.2
  script: |
    python build.py --rocmrelease=5.1.0
requirements:
  build:
    - python
    - libstdcxx-ng
    - libgcc-ng
    - zlib
  run:
    - python
    - libstdcxx-ng
    - libgcc-ng
    - rocm-llvm
    - rocblas
outputs:
  - name: rocm-llvm
    files:
      - llvm
      - share/doc/rocm-llvm
      - bin/amdclang*
      - bin/amdflang
      - bin/amdlld
  - name: rocblas
    files:
      - rocblas
      - share/doc/rocblas
      - lib/librocblas*
      - lib/library/Kernels.so*
      - lib/library/Tensile*