{% set version = environ.get('CONDA_ROCM_VERSION', '5.1.0') %}
{% set string_a = environ.get('PACKAGES_BUILD_STRING_A', '') %}
{% set string_b = environ.get('PACKAGES_BUILD_STRING_B', '') %}
{% if string_b != '' %}
  {% set string_b = '_' + string_b %}
{% endif %}

package:
  name: rocm-language-runtime
  version: {{ version }}
source:
  path: .
build:
  number: 0
{% if string_a != '' %}
  string: +{{ string_a }}_py{{ CONDA_PY }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% else %}
  string: py{{ CONDA_PY }}{{ string_b }}_{{ PKG_BUILDNUM }}
{% endif %}
  missing_dso_whitelist:
    - $RPATH/librt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libpthread.so.0
    - $RPATH/libtinfo.so.5
    - $RPATH/libm.so.6
    - $RPATH/libc.so.6
    - $RPATH/libelf.so.1
    - $RPATH/libdrm.so.2
    - $RPATH/libdrm_amdgpu.so.1
    - $RPATH/libnuma.so.1
    - /lib64/ld-linux-x86-64.so.2
  script: |
    python build.py --rocmrelease={{ version }}
requirements:
  build:
    - libstdcxx-ng
    - libgcc-ng
    - python
    - zlib
  run:
    - libstdcxx-ng
    - libgcc-ng
    - python